### PR TITLE
Implementation of QWindow

### PR DESCRIPTION
**Pull request by noisesource**
This adds implementation for `QWindow` methods.

For more information about new methods, see `ROADMAP.org`.

### CODE REVIEW

**Comment by aartaka** [comment]
Looks good to me.

But what's the information about new methods that you said now is in `ROADMAP.org` file? The only change I see is the change of checkboxes :eyes:

**Comment by noisesource** [comment]
>But what's the information about new methods that you said now is in `ROADMAP.org` file?

This is the information about the relation of Qt methods to wrapper function names. Indeed, you can find it inside `interface.h/cpp` files, but `ROADMAP.org` has it in a bit more organized way. :) 

> The only change I see is the change of checkboxes.

Mostly yes, but I also added the `windowShow` function to the `ROADMAP.org` file.

**Comment by aartaka** [comment]
OK, got it now.

**Comment by Ambrevar** [comment]
Looks good to me too, thanks! :)

**Pull request merged**
